### ISSUE TITLE
Issue with BMI train (ImportError: cannot import name 'cli_for_train' from 'pht.entrypoint')

### ISSUE THREAD

**Issue by rezacsedu** [PersonalHealthTrain/train-api-python#4]
$  sudo docker build -t miibmi:pht .
$ sudo docker run miibmi:pht --station-id 1 run
Traceback (most recent call last):
  File "/opt/entrypoint.py", line 16, in <module>
    from pht.entrypoint import cli_for_train
ImportError: cannot import name 'cli_for_train' from 'pht.entrypoint' (/usr/local/lib/python3.7/site-packages/pht-1.0rc3-py3.7.egg/pht/entrypoint.py)

Am I doing something wrong?

**Comment by rezacsedu** [comment]
Using RC4 and some manual effort, I managed to make it running and the BMI is computed. But still, it gives the following errors:

....
BMI file has been generated!
....
Traceback (most recent call last):
  File "/opt/entrypoint.py", line 238, in <module>
    cmd_for_train(BMITrain())
  File "/usr/local/lib/python3.7/site-packages/pht-1.0rc4-py3.7.egg/pht/entrypoint.py", line 26, in cmd_for_train
    _fprint(train.run(info).to_json_string())
  File "/opt/entrypoint.py", line 232, in run
    export_files=[self.bmi_file]
  File "/usr/local/lib/python3.7/site-packages/pht-1.0rc4-py3.7.egg/pht/rebase/DockerRebaseStrategy.py", line 11, in __init__
    super().__init__(next_train_tags, export_files)
  File "/usr/local/lib/python3.7/site-packages/pht-1.0rc4-py3.7.egg/pht/rebase/RebaseStrategy.py", line 73, in __init__
    self._validate_next_train_tags(next_train_tags)
  File "/usr/local/lib/python3.7/site-packages/pht-1.0rc4-py3.7.egg/pht/rebase/RebaseStrategy.py", line 108, in _validate_next_train_tags
    raise TypeError('\'tags\' for Rebase Strategy must be a List of str values')
TypeError: 'tags' for Rebase Strategy must be a List of str values

**Comment by lukaszimmermann** [comment]
Solved with the latest RC5
